version: "3.9"
services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"
    depends_on:
      - user-db

  post-service:
    build: ./services/post-service
    ports:
      - "3002:3002"
    environment:
      - MINIO_ENDPOINT=minio
    depends_on:
      - post-db
      - minio
      - notif-db
      - user-db

  notification-service:
    build: ./services/notification-service
    ports:
      - "5002:5002"
    depends_on:
      - post-db
      - notif-db
      - user-db


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

    
  user-db:
    image: mongo:latest
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db

  post-db:
    image: mongo:latest
    container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db

  notif-db:
    image: mongo:latest
    container_name: notif-db
    ports:
      - "27019:27017"
    volumes:
      - notif-data:/data/db

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - post-service
      - notification-service

volumes:
  user-data:
  post-data:
  notif-data:
  minio_data:

# The updated project ensures MongoDB is used as the database for all services, with MinIO for object storage where needed.
